import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core'

export const systemConfig = sqliteTable('system_config', {
  id: text('id').primaryKey().default('global'),
  smtpHost: text('smtp_host'),
  smtpPort: integer('smtp_port'),
  smtpUser: text('smtp_user'),
  smtpPass: text('smtp_pass'),
  smtpFromEmail: text('smtp_from_email'),
  smtpFromName: text('smtp_from_name'),
  captchaProvider: text('captcha_provider').notNull().default('none'),
  turnstileSiteKey: text('turnstile_site_key'),
  turnstileSecretKey: text('turnstile_secret_key'),
  recaptchaSiteKey: text('recaptcha_site_key'),
  recaptchaSecretKey: text('recaptcha_secret_key'),
  geetestCaptchaId: text('geetest_captcha_id'),
  geetestCaptchaKey: text('geetest_captcha_key'),
  capSiteKey: text('cap_site_key'),
  capSecretKey: text('cap_secret_key'),
  capVerifyUrl: text('cap_verify_url'),
  altchaSiteKey: text('altcha_site_key'),
  altchaSecretKey: text('altcha_secret_key'),
  hcaptchaSiteKey: text('hcaptcha_site_key'),
  hcaptchaSecretKey: text('hcaptcha_secret_key'),
  jwtSecret: text('jwt_secret'),
  globalSystemPrompt: text('global_system_prompt'),
  emailNotifyComments: integer('email_notify_comments', { mode: 'boolean' }).notNull().default(false),
  registrationOpen: integer('registration_open', { mode: 'boolean' }).notNull().default(false),
  allowedOrigins: text('allowed_origins', { mode: 'json' }),
  rateLimitMax: integer('rate_limit_max').notNull().default(100),
  rateLimitWindow: integer('rate_limit_window').notNull().default(60),
  providerDefaults: text('provider_defaults'),
  updatedAt: text('updated_at'),
})
